### ISSUE TITLE
use a python PEP 8 compliant opinionated formatter

### ISSUE THREAD

**Issue by Prakashdeveloper03** [Vgokulapriya/PYTHON-PROGRAM#1]
use a PEP 8-compliant formatter for formatting python
[https://black.readthedocs.io/en/stable/the_black_code_style/index.html](https://black.readthedocs.io/en/stable/the_black_code_style/index.html)

**Comment by Vgokulapriya** [comment]
all files are reformatted. ISSUE CLOSED
